"""Generate planted Hawkes streams, fit, print Hawkes vs Poisson, write metrics.json."""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

import numpy as np

from hawkes_bursts import const
from hawkes_bursts.ablate import ablation, print_table
from hawkes_bursts.eval import evaluate, print_report
from hawkes_bursts.simulate import simulate_exp_hawkes

METRICS = "metrics.json"
METRICS_TS = "web/src/metrics.gen.ts"

ABLATION_LABEL = {
    "poisson": "Poisson (no kernel)",
    "exp_mu_frozen": "Exp, μ frozen",
    "exp_mu_misspec": "Exp, μ at 2× rate",
    "exp_full": "Exp, μ fitted",
}


def sample_trace():
    rng = np.random.default_rng(const.SEED + 99)
    times = simulate_exp_hawkes(const.MU, const.ALPHA, const.BETA, 80, rng)
    t_end = min(float(times[-1]), 16.0)
    grid = np.linspace(0.0, t_end, 160)
    hawkes = []
    for t in grid:
        past = times[times < t]
        hawkes.append(float(const.MU + const.ALPHA * np.exp(-const.BETA * (t - past)).sum()))
    rate = len(times) / float(times[-1])
    events = times[times <= t_end]
    return {
        "t": [round(float(x), 4) for x in grid],
        "hawkes": [round(x, 4) for x in hawkes],
        "poisson": [round(rate, 4)] * len(grid),
        "events": [round(float(x), 4) for x in events],
    }


def write_metrics_ts(m, rows, trace):
    if not os.path.isdir("web/src"):
        return
    ab = []
    for r in rows:
        ab.append(
            {
                "model": r["model"],
                "label": ABLATION_LABEL[r["model"]],
                "kernel": r["kernel"],
                "mu": r["mu"],
                "llHoldout": round(r["ll_holdout"], 4),
                "successPct": round(r["success_pct"], 2),
            }
        )
    body = f"""// Generated by scripts/run.py. Do not hand-edit.

export const ILLUSTRATIVE = false

export const PROTOCOL = {{
  trainFrac: {m["train_frac"]},
  maxEvents: {const.MAX_EVENTS},
  maxStreams: {const.MAX_STREAMS},
  floorPct: {const.FLOOR_PCT},
}}

export const METRICS = {{
  successPct: {m["success_pct"]},
  poissonPct: 0,
  nStreams: {m["n_streams"]},
  nEvents: {m["n_events"]},
  nTrain: {m["n_train"]},
  nTest: {m["n_test"]},
  llHawkes: {round(m["ll_hawkes"], 4)},
  llPoisson: {round(m["ll_poisson"], 4)},
  muHat: {round(m["mu_hat"], 4)},
  alphaHat: {round(m["alpha_hat"], 4)},
  betaHat: {round(m["beta_hat"], 4)},
}}

export const ABLATION = {json.dumps(ab, ensure_ascii=False)} as const

export const TRACE = {json.dumps(trace, ensure_ascii=False)}
"""
    with open(METRICS_TS, "w", encoding="utf-8") as f:
        f.write(body)


def main():
    m = evaluate()
    rows = ablation(n_streams=m["n_streams"], n_events=m["n_events"], seed=m["seed"])
    out = {k: v for k, v in m.items() if k != "rows"}
    out["ablation"] = rows
    with open(METRICS, "w") as f:
        json.dump(out, f, indent=2)
    write_metrics_ts(m, rows, sample_trace())
    print_report(m)
    print_table(rows)
    if m["n_events"] > const.MAX_EVENTS or m["n_streams"] > const.MAX_STREAMS:
        sys.exit("HARD FAIL: cap exceeded")


if __name__ == "__main__":
    main()
